apiVersion: v1
kind: Namespace
metadata:
  name: postgres
---
apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
  name: postgres
  namespace: postgres
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: idp/postgres
      versionId: 73def933-396d-4925-bdd4-1a91b57137e1
