apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-imdb
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ""
    namespace: api-imdb
    server: https://kubernetes.default.svc
  source:
    path: helm/
    repoURL: https://github.com/jppol-idp/api-imdb
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
